### ISSUE TITLE
!wild not working the same

### ISSUE THREAD

**Issue by 1lwebstudio** [FoglyOgly/Meowth#116]
Hello,

Recently the !wild stopped working on my discord server. 

I am using PokeAlarm to alert of spawns and I was using this alert to also include !wild Pokémon address city 
This has been working very well until recently. 

May I know what has changed that has stopped Meowth from recognising a bot using your commands?

Thank you

**Comment by 1lwebstudio** [comment]
Please be aware that !wild works if I message it in the channel in discord.

**Comment by 1lwebstudio** [comment]
Also last working date was 10 Jan 2018

**Comment by scragly** [comment]
Meowth has never supported or recommended bots interacting directly with it. It's also common for bots to ignore other bots for commands, due to possible rate abuse, usage control, prevention of accidental loops, and avoidance of other conflicts

Meowth was also created while specifically upholding the ideal to respect the Terms of Service of both the game and the associated accounts.

Any spoofer services such as Gym/Pokemon Trackers, such as your PokeAlarm as you've admitted using, are absolutely against TOS and as such is in direct conflict with the purpose of Meowth.
