### ISSUE TITLE
Inherit Channel Permissions

### ISSUE THREAD

**Issue by cr15topher** [FoglyOgly/Meowth#21]
Something that people keep complaining about is all the new channels constantly notifying them when they are created. I know there is a way to change the permissions of a channel after creating it and also a way to create a private channel and that server notification settings fix this, but there are some benefits to improving this process. This would keep these channels hidden on servers where channels are area specific and are hidden unless the user opts-in to a certain role.

http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.create_channel
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.edit_channel_permissions

I'll be working on this, if anyone else makes any progress please let me know.

**Comment by FoglyOgly** [comment]
The current master branch already has raid channels inherit permission
overwrites from the channel the raid was reported in, so all you should
have to do is make permissions for each area channel that keep people from
seeing areas they aren't opted in on, like you said. This is a recent
change though so you may just need the latest commits.

On Aug 16, 2017 7:51 AM, "cr15topher" <notifications@github.com> wrote:

Something that people keep complaining about is all the new channels
constantly notifying them when they are created. I know there is a way to
change the permissions of a channel after creating it and also a way to
create a private channel and that server notification settings fix this,
but there are some benefits to improving this process. This would keep
these channels hidden on servers where channels are area specific and are
hidden unless the user opts-in to a certain role.

http://discordpy.readthedocs.io/en/latest/api.html#discord.
Client.create_channel
http://discordpy.readthedocs.io/en/latest/api.html#discord.
Client.edit_channel_permissions

I'll be working on this, if anyone else makes any progress please let me
know.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FoglyOgly/Meowth/issues/21>, or mute the thread

**Comment by cr15topher** [comment]
Ah, great, I'll look over the code again. I was still running an earlier version and started working with the new one making some changes today. Haven't actually pushed this latest version to production.
