### ISSUE TITLE
[feature request] Allow stop/gym aliases

### ISSUE THREAD

**Issue by efenderbosch** [FoglyOgly/Meowth#213]
My players generally abbreviate gym/stop names. When new players join, this can be confusing because the google map search might not be correct. It would be nice if we could somehow through json/yaml or whatever specific a lat/long or address and list of aliases for stops/gyms. If an alias is defined, then use lat/long or address instead of a google maps search.

Or a ! command?
`!alias add "stop name goes here" lat,long (or addresss)`
`!alias remove "gym name goes here"`
`!alias listall`

**Comment by kwilliams147** [comment]
Looking though some of the code it looks like this is a thing if you self host the bot. If you self host it would go in data/gym_data.json there is an example file for formatting.

**Comment by scragly** [comment]
Yep, as @kwilliams147 stated, there's an example implementation in the bot at the moment that was added on request in our support server and when I had some spare time. The implementation however isn't complete and would require a bit of tweaking to get perfected, such as the alterations missing from the exraid reports.

It's also definitely only possible to do at this stage if you're self-hosting, as we don't want to store and manage the gym data in json files of more than 2500 discord servers, as it would get a bit over the top. 

Our next major version update will implement gym matching though as part of the live bot, but we don't have an immediate ETA on that. 

Since gym matching is a definite on our next major version and will be available on release, I'll close this issue and you're welcome to keep up to date either by watching the github version updates, or by joining our discord support server and waiting for the announcement.
